### DISCUSSION TITLE
let use can change `spring.profiles.active`'s value without rebuild the project

### DISCUSSION THREAD

**Discussion by Anilople** [apolloconfig/apollo#4610] [General]
in https://github.com/apolloconfig/apollo/blob/67030ba4867d34b25d5fdc5b6c02a65b6c7d759c/apollo-configservice/src/main/resources/application.yml
```yaml
spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
```

`${apollo_profile}` will be resolved when build the project.

Could we let use can change `spring.profiles.active`'s value without rebuild the project?

When user want to use consul-discovery, zookeeper-discovery or custom-defined-discovery, they only need to change the config instead of rebuild the project again.
