### DISCUSSION TITLE
Apollp Portal的email邮件服务应该怎么接AWS SES

### DISCUSSION THREAD

**Discussion by kyleli666** [apolloconfig/apollo#5413] [Q&A] [answered]
我们用的AWS SES服务，smtp配置信息如下
```yaml
SMTP endpoint: xxxxxxxxxxx.amazonaws.com
Transport Layer Security (TLS): Required
STARTTLS Port: 25, 587 or 2587
TLS Wrapper Port: 465 or 2465
```

测试发邮件的时候看日志，似乎Portal始终连接25端口，在文档里似乎也没有找到足够的配置项可以支持这些配置
https://www.apolloconfig.com/#/zh/extension/portal-how-to-enable-email-service?id=_11-%e6%8e%a5%e5%85%a5%e6%ad%a5%e9%aa%a4

求助应该怎么配置能用上AWS SES？

---
https://docs.aws.amazon.com/zh_cn/ses/latest/dg/send-using-smtp-programmatically.html
