### ISSUE TITLE
Load config failed Could not complete get operation Cause: Read timed out

### ISSUE THREAD

**Issue by 8823Senior** [apolloconfig/apollo#4004]
**描述bug**

ECS 部署 docker-quick-start

本地通过 ECS 公网 IP 访问，日志却打印出按 docker 容器 ip 去拉取配置，导致拉取超时
debug 日志看到居然是通过 docker 容器 ip 172.27.0.2:8080 请求数据？ 
***这种场景使用时，是否需要更改其他配置***

 -Dapollo.meta=http://公网ip:18080 -Denv=DEV 

> 控制台日志
Located meta services from apollo.meta configuration: http://公网ip:18080!
No available properties: apollo-env.properties
Located meta server address http://公网ip:18080 for env DEV from com.ctrip.framework.apollo.internals.DefaultMetaServerProvider
Loading config from http://172.27.0.2:8080/configs/dynamic-datasource/default/application?ip=192.168.30.203
Load config failed, will retry in 1 SECONDS. appId: dynamic-datasource, cluster: default, namespaces: application
Loading config from http://172.27.0.2:8080/configs/dynamic-datasource/default/application?ip=192.168.30.203
Sync config failed, will retry. Repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository, reason: Load Apollo Config failed - appId: dynamic-datasource, cluster: default, namespace: application, url: http://172.27.0.2:8080/configs/dynamic-datasource/default/application?ip=192.168.30.203 [Cause: Could not complete get operation [Cause: Read timed out]]

```yaml
version: '2'

services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-quick-start
    depends_on:
      - apollo-db
    ports:
      - "18080:8080"
      - "18090:8090"
      - "18070:8070"
    links:
      - apollo-db

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - apollo-dbdata

  apollo-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
      - /var/lib/mysql
```
