### ISSUE TITLE
docker swarm configservice 报错

### ISSUE THREAD

**Issue by seqwait** [apolloconfig/apollo#4127]
compose 文件:
```
version: "3.7" # optional since v1.27.0
services:
  apollo_configservice_dev:
    image: apolloconfig/apollo-configservice
    ports:
      - "8081:8080"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://apollo_mysql/ApolloConfigDB_Dev?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_INSTANCE_HOME_PAGE_URL: http://apollo_configservice_dev:8081
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_INSTANCE_IP_ADDRESS: "apollo_configservice_dev"
    networks:
       overall_test:

  apollo_adminservice_dev:
    image: apolloconfig/apollo-adminservice
    ports:
      - "8090:8090"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://apollo_mysql/ApolloConfigDB_Dev?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_INSTANCE_HOME_PAGE_URL: http://apollo_adminservice_dev:8090
      EUREKA_INSTANCE_IP_ADDRESS: "apollo_configservice_dev"
    networks:
      overall_test:

  apollo_configservice_prod:
    image: apolloconfig/apollo-configservice
    ports:
      - "8082:8080"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://apollo_mysql/ApolloConfigDB_Prod?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_INSTANCE_HOME_PAGE_URL: http://apollo_configservice_prod:8082
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_INSTANCE_IP_ADDRESS: "apollo_configservice_prod"
    networks:
      overall_test:

  apollo_adminservice_prod:
    image: apolloconfig/apollo-adminservice
    ports:
      - "8091:8090"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://apollo_mysql/ApolloConfigDB_Prod?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      EUREKA_INSTANCE_HOME_PAGE_URL: http://apollo_adminservice_prod:8091
      EUREKA_INSTANCE_IP_ADDRESS: "apollo_configservice_prod"
    networks:
      overall_test:

  apollo_portal:
    image: apolloconfig/apollo-portal
    ports:
      - "8070:8070"
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: "jdbc:mysql://apollo_mysql/ApolloPortalDB?characterEncoding=utf8"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      APOLLO_PORTAL_ENVS: FAT,PRO
    networks:
      overall_test:

networks:
  overall_test:
    external: true
    name: overall_test
    attachable: true
```

报错信息:

2021-12-03 18:29:30.650  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_APOLLO-CONFIGSERVICE/10.0.0.148:apollo-configservice:8080: registering service...
2021-12-03 18:29:30.651  INFO 1 --- [nfoReplicator-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://apollo_configservice_prod:8080/eureka/}, exception=java.lang.IllegalArgumentException: Host name may not be null stacktrace=com.sun.jersey.api.client.ClientHandlerException: java.lang.IllegalArgumentException: Host name may not be null
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
