### ISSUE TITLE
整合两台独立部署的apollo configserver

### ISSUE THREAD

**Issue by GitHub-lzy** [apolloconfig/apollo#4168]
有两台独立部署的apollo，一台甲方提供，用于维护公共配置；一台独立部署，用于维护私有配置；二者参数没有交集且互补
想问下各位老师：
是否可以实现整合两个apollo.meta地址，启动后cacheDir可获取两台apollo的参数，且同时订阅两台apollo的参数；
尝试过nginx反向代理加轮询负载，但是由于参数没有交集，启动只能获取其中一台的参数到cacheDir，并且五分钟内只能订阅其中一台的apollo参数，时效性做不到保证

**Comment by Anilople** [comment]
You mean client can collect multiple apollo config services config?

i.e

```
apollo:
  metas:
    meta1: http://xxx
    meta2: http://yyy
```

Make an union calculate to collect all configs to client?
