### ISSUE TITLE
apollo支持yaml格式的配置么

### ISSUE THREAD

**Issue by jiangxiaoqiang** [apolloconfig/apollo#4236]
例如我的配置长这样：

```
spring:
   cloud:
      gateway:
         routes:
            -
               id: dolphin-dict-service
               uri: http://10.97.100.34:11014/
               predicates:
                  - Path=/dict/**
               filters:
                  -
                     name: JwtAuthentication
```

现在好像不支持,阅读了文档，但是里面没有说明如何使用yaml格式
