### ISSUE TITLE
项目引用多个namespace时，A引用了B的某个属性，结果有时候会启动失败获取不到

### ISSUE THREAD

**Issue by a937282042** [apolloconfig/apollo#4471]
我在项目中做了如下配置
```
app:
  id: xxx
apollo:
  cacheDir: /var/apollo/
  cluster: default
  autoUpdateInjectedSpringProperties: true
  meta: http://xxxxxxx:8080
  bootstrap:
    enabled: true
    namespaces: xxxServers.yml,application.yml
    eagerLoad:
      enabled: true
```
在代码中使用
```
	@Value("${test}")
	private String hisAlarmUrl;
```
在xxxServers.yml中配置如下
```
#测试
test: http://127.0.0.1;123456
```
项目启动正常 但是有的时候项目启动报错  hisAlarmUrl 无法获取多次多次重启无效 最后只能写到了项目的application.yml中
报错信息
`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'test' in value "${test}" 
`
