### ISSUE TITLE
openjdk:8-jre-alpine 导致 `Runtime.getRuntime().availableProcessors()` 获取到的 CPU 核数不准确

### ISSUE THREAD

**Issue by klboke** [apolloconfig/apollo#4474]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

openjdk:8-jre-alpine 镜像导致 `Runtime.getRuntime().availableProcessors()` 获取到的 CPU 核数不准确，如在 k8s 里定义 4C：
```yaml
  resources:
    requests:
      cpu: 4
      memory: 6Gi
    limits:
      cpu: 4
      memory: 6Gi
```
程序里只返回了 2C
**复现**

通过如下步骤可以复现：

1. 在 k8s 里启动 Apollo 服务， requests 、limits 都限制 4C
2. 访问 Portal 的 /prometheus 接口
3. 查看 system_cpu_count 指标，是否和 limits 吻合
4. 

**期望**
修改基础镜像为：openjdk:8-jre-slim
