### ISSUE TITLE
openapi增加yaml配置的相关接口

### ISSUE THREAD

**Issue by gp0014** [apolloconfig/apollo#4511]
**你的特性请求和某个问题有关吗？请描述**

在对yaml类型的配置做修改发布的时候，没有相应的openapi接口，只有kv的接口

**清晰简洁地描述一下你希望的解决方案**

希望提供openapi接口来对yaml配置做操作。

**Comment by nobodyiam** [comment]
non-properties namespace is a special properties namespace that the key is `content` and the value is the whole context.

e.g. you could use the namespace name `application.yaml` to retrieve the yaml namespace in [apollo-demo](http://106.54.227.205/config.html?#/appid=100004458) site.

```
OpenNamespaceDTO{appId='100004458', clusterName='default', namespaceName='application.yaml', comment='', format='yaml', isPublic=false, items=[OpenItemDTO{key='content', value='redis:
  cache:
    enabled: true
    expireSeconds: 3010
    clusterNodes: 1,2
    commandTimeout: 200
    someMap:
      key1: aa
      key2: bb
    someList:
    - c
    - d', comment='null', dataChangeCreatedBy='apollo', dataChangeLastModifiedBy='apollo', dataChangeCreatedTime=Sun Jan 16 12:44:21 CST 2022, dataChangeLastModifiedTime=Sun Jul 03 08:58:59 CST 2022}], dataChangeCreatedBy='apollo', dataChangeLastModifiedBy='apollo', dataChangeCreatedTime=Sun Jan 16 12:43:18 CST 2022, dataChangeLastModifiedTime=Sun Jan 16 12:43:18 CST 2022}
```
