### ISSUE TITLE
接入oidc登录后apollo-portal启动失败

### ISSUE THREAD

**Issue by chenjinxuan** [apolloconfig/apollo#4561]
接入oidc登录后apollo-portal启动失败
在k8s使用helm部署

挂载配置文件
```
config:
  profiles: "github,oidc"
  files:
    application-oidc.yml: |
      server:
         forward-headers-strategy: framework
      spring:
         security:
           oauth2:
             client:
               provider:
                 passport:
                    issuer-uri: https://xxx.xxx/xxx
               registration: 
                 passport:
                    authorization-grant-type: authorization_code
                    client-authentication-method: basic
                    client-id: xxx
                    provider: passport
                    scope:
                      - openid
                    client-secret: xxxxxx
```
启动后报错
![image](https://user-images.githubusercontent.com/25172225/189279927-fa4532e4-2342-420c-9110-51dfe42f6cf5.png)

### 额外的细节和日志

- 版本：apollo-portal 2.0.1
- 错误日志
- 配置：
- 平台和操作系统   k8s
