### ISSUE TITLE
Windows Active Directory接入LDAP 方式,报用户名或密码错误[已解决]

### ISSUE THREAD

**Issue by lxtima** [apolloconfig/apollo#4635]
更新：
问题已经解决，配置没问题，确实是LDAP账号密码错误

---------------------------------------------------------------------------

如下配置完成后，服务启动无异常，日志没报异常，但是无论用apollo系统用户账号和密码登录，还是使用LDAP账号密码登录，均报用户名和密码错误，且日志无异常或任何输出。

禁用ldap参数启动后，使用系统账号，如：apollo账号就可以正常登录。

反复核对过ladp配置信息，没发现有不对的地方啊，可以确定域管理员账号，密码(16位)，地址，端口都是正确的(因为其他几个正在使用的系统LDAP登录是正常的)。

不知道是什么情况，请教一下，还有哪里可能出现问题？

**/opt/apollo/portal-2.0.1/config/application-ldap.yml 配置文件：**
**base，password，url信息请忽略...**
```
spring:
  ldap:
    base: "dc=cctv,dc=com"
    username: "LDAPadmin"
    password: "password"
    searchFilter: "(sAMAccountName={0})"
    urls:
    - "ldap://192.168.1.150:389"
ldap:
  mapping:
    objectClass: "user"
    loginId: "sAMAccountName"
    userDisplayName: "cn"
    email: "mail"
```

**启动文件：/opt/apollo/portal-2.0.1/scripts/startup.sh**
```
export JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=github,ldap"
export JAVA_OPTS="$JAVA_OPTS -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=9 -XX:+DisableExplicitGC -XX:+ScavengeBeforeFullGC -XX:SoftRefLRUPolicyMSPerMB=0 -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Duser.timezone=Asia/Shanghai -Dclient.encoding.override=UTF-8 -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom"
```
