### ISSUE TITLE
[Feature request] need an apollo-operator for LCM by cloud native way

### ISSUE THREAD

**Issue by wilsonwu** [apolloconfig/apollo#4696]
**Is your feature request related to a problem? Please describe.**
Under Cloud Native world, it is hard to manage apollo instances.

**Describe the solution you'd like**
Create an operator to do LCM.

**Describe alternatives you've considered**
Also can do LCM by k8s apis, but it is hard and inefficient.

**Additional context**
No more.

**Comment by nobodyiam** [comment]
Sounds a good idea.

**Comment by JaredTan95** [comment]
hi, @wilsonwu,
Agree with your suggestion, Operator is currently the most common way for cloud-native, and happy to see the `Apollo-Operator` sub-project, but, before that, we need to have a rough design that allows other apollo PMC members of the community to participate in the review.

From my understanding, I roughly think that the operator should include the following `CRD` or cr resources, just for reference:

- ApolloEnvironment: configservice/k8s-metaservice + adminservice
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: k8s.apolloconfig.com/v1
kind: AplloEnvironment
metadata:
  name: quickstart-apollo-env
spec:
  version: xxx
  count: 1
  mysql:
    host: my-apollo-mysql-db
    dbname: apollo_config
  # mysqlRef can ref a mysql instance created by operator either.
  #mysqlRef:
  #    name:  quickstart-apollo-mysql
EOF
```
- AplloPortal:  portal service 
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: k8s.apolloconfig.com/v1
kind: AplloPortal
metadata:
  name: quickstart
spec:
  version: 0.0.1
  count: 1
  mysql:
    host: my-apollo-mysql-db
    dbname: apollo_config
  # mysqlRef can ref a mysql instance created by operator either.
  #mysqlRef:
  #    name:  quickstart-apollo-mysql
  apolloEnvRef:
    name: quickstart-apollo-env
EOF
```

- All-In-One(configservice + admin + portal + memory/DB) for demo
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: k8s.apolloconfig.com/v1
kind: Apllo
metadata:
  name: quickstart
spec:
  version: 0.0.1
  count: 1
EOF
```

BTW, It is also worth mentioning that `apollo` involves some writes and reads of the database, which is a more complex, I think that the early of the operator can avoid this part of the operation when doing apollo upgrade and unload, and inform users how to manually clean the database in the form of documents. @nobodyiam What do you think？
