### ISSUE TITLE
is it possible to read parent or Map<String,List<String>> from yaml

### ISSUE THREAD

**Issue by jiangxiaoqiang** [apolloconfig/apollo#4853]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

when I tried to read a `Map<String,List<String>>` structure, seems it did not work.

**复现**

通过如下步骤可以复现：

this is a minimal reproduce example:

```
package com.example.demo;


import com.ctrip.framework.apollo.spring.annotation.EnableApolloConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * @author xiaoqiangjiang
 */
@SpringBootApplication
@EnableApolloConfig(value = {"application-yaml.yaml"})
public class DemoApplicationSlim {
	public static void main(String[] args) throws Exception {
		SpringApplication.run(DemoApplicationSlim.class, args);
	}
}

```

and this is the demo controller:

```
package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping("/post/")
public class DemoController {

    @Autowired
    private LoginExcludeUrl loginExcludeUrl;

    @GetMapping("/user")
    String getQRCodeUrl(){
        var r =loginExcludeUrl.getExclude("post");
        return "hello world";
    }

}

```

and this is the how the configure readed:

```
package com.example.demo;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author xiaoqiangjiang
 */
@ConfigurationProperties(prefix = "dolphin.gateway.login-check-path")
@Component
public class LoginExcludeUrl {

    private Map<String,List<String>> exclude = new HashMap<>();

    public List<String> getExclude(String appPrev) {
        return exclude.get(appPrev);
    }

}

```

and this is how the yaml configure:

```
apollo:
  bootstrap:
    eagerLoad:
      enabled: true
    enabled: true
    namespaces: application-yaml.yaml,TEST1.EUREKA,TEST1.REDIS-CONFIG,TEST1.DATASOURCE-DRUID
app:
  id: 0010010002
spring:
  application:
    name: demo
    server:
      port: 11018
dolphin:
  gateway:
    login-check-path:
      a:
        - c
        - d
      b:
        - e
        - f

```

**期望**

简介明了地描述你希望正常情况下应该发生什么

what I wanted is that the excude url could have 2 keys a and b and each of the key contains a List that contains the subelement. is it possible? or am I missing something?

**截图**

<img width="971" alt="image" src="https://user-images.githubusercontent.com/4521375/233558902-b0f8dc2d-b888-4086-b98c-75bae4b9caa8.png">

### 额外的细节和日志

- 版本：1.8.0
- 错误日志
- 配置：
- 平台和操作系统 macOS 13

BTW, I also tried to tweak the config like this:

```
apollo:
  bootstrap:
    eagerLoad:
      enabled: true
    enabled: true
    namespaces: application-yaml.yaml,TEST1.EUREKA,TEST1.REDIS-CONFIG,TEST1.DATASOURCE-DRUID
app:
  id: 0010010002
spring:
  application:
    name: demo
    server:
      port: 11018
dolphin:
  gateway:
    login-check-path:
      exclude:
        a:
          - c
          - d
        b:
          - e
          - f

```
