### ISSUE TITLE
snakeyaml历史版本漏洞，升级2.x后存在兼容性问题

### ISSUE THREAD

**Issue by yonglong-zhang** [apolloconfig/apollo#4960]
我在引入了apollo-client 2.1.0后发现snakeyaml的版本还是使用的1.29，故升级snakeyaml版本为2.x，但是升级到2.x后，存在兼容性问题

代码文件：[YamlParser.java](https://github.com/apolloconfig/apollo-java/blob/main/apollo-client/src/main/java/com/ctrip/framework/apollo/util/yaml/YamlParser.java)

**Comment by yonglong-zhang** [comment]
Init Apollo Local Config failed - namespace: application.yml, reason: Parse yaml file content failed for namespace: application.yml [Cause: org.yaml.snakeyaml.constructor.SafeConstructor: method <init>()V not found].

**Comment by nobodyiam** [comment]
看起来是 snakeyaml 大版本升级后删除了 SafeConstructor 的默认构造函数，建议升级到 1.x 的最新版本吧

**Comment by richieyan** [comment]
> 看起来是 snakeyaml 大版本升级后删除了 SafeConstructor 的默认构造函数，建议升级到 1.x 的最新版本吧

目前 snakeyaml 1.x 已经没有合适的最新版本可以使用，必须使用 2.x 的版本

**Comment by nobodyiam** [comment]
Apollo java version 2.2.0 is now available for download. You can access this latest release at [Maven Central](https://search.maven.org/search?q=com.ctrip.framework.apollo).

**Comment by walkertest** [comment]
> Apollo java version 2.2.0 is now available for download. You can access this latest release at [Maven Central](https://search.maven.org/search?q=com.ctrip.framework.apollo).

请问这块是怎么建议的.
如果升级了apllo的依赖，因为spring也依赖snakeyaml，是不是也得强制升级spring等相关依赖.

怎么兼容呢，换一个新的yaml解析库吗

**Comment by nobodyiam** [comment]
Which version of Spring are you currently utilizing? I assume it would be compatible with the majority of Spring versions.

**Comment by GhostBoyBoy** [comment]
> Which version of Spring are you currently utilizing? I assume it would be compatible with the majority of Spring versions.

Hi, I also encountered it. My version is also Apollo 2.1, spring boot is 3.2.0, spring cloud 2023.0.0

**Comment by GhostBoyBoy** [comment]
> > Which version of Spring are you currently utilizing? I assume it would be compatible with the majority of Spring versions.
> 
> Hi, I also encountered it. My version is also Apollo 2.1, spring boot is 3.2.0, spring cloud 2023.0.0

I have many spring cloud gateway configurations

**Comment by GhostBoyBoy** [comment]
2023-12-14 21:31:48.401 [] [main] WARN  c.ctrip.framework.apollo.internals.DefaultConfig - Init Apollo Local Config failed - namespace: application.yml, reason: Parse yaml file content failed for namespace: application.yml [Cause: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found].

**Comment by GhostBoyBoy** [comment]
`spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      clients:
        app1:
          hint:
            enable: true
            gray: 100
        app2:
          hint:
            enable: false
            gray: 100

    gateway:
      httpclient:
        response-timeout: 300s

      routes:
        - id: app1-serv
          uri: lb://app1 # 使用Eureka服务名负载均衡
          predicates:
            - Path=/app1/**
          filters:
            - RewritePath=/app1(?<segment>/?.*), $\{segment}
            - AddNginxRequestHeader=X-Real-IP,$
        - id: app2
          uri: lb://app2
          predicates:
            - Path=/app2/**
          filters:
            - RewritePath=/app2(?<segment>/?.*), $\{segment}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3  # 服务实例向Eureka Server发送心跳的时间间隔，默认为30秒
    leaseExpirationDurationInSeconds: 3  # Eureka Server在收不到服务实例的心跳后将其剔除的时间，默认为90秒
  client:
    registryFetchIntervalSeconds: 3
    instanceInfoReplicationIntervalSeconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka服务器地址

server:
  port: 8080 # Gateway服务器端口

logging:
  config: classpath:logback.xml
  level:
    com.mishu: info`

**Comment by GhostBoyBoy** [comment]
`
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      clients:
        app1:
          hint:
            enable: true
            gray: 100
        app2:
          hint:
            enable: false
            gray: 100

    gateway:
      httpclient:
        response-timeout: 300s

      routes:
        - id: app1-serv
          uri: lb://app1 # 使用Eureka服务名负载均衡
          predicates:
            - Path=/app1/**
          filters:
            - RewritePath=/app1(?<segment>/?.*), $\{segment}
            - AddNginxRequestHeader=X-Real-IP,$
        - id: app2
          uri: lb://app2
          predicates:
            - Path=/app2/**
          filters:
            - RewritePath=/app2(?<segment>/?.*), $\{segment}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3  # 服务实例向Eureka Server发送心跳的时间间隔，默认为30秒
    leaseExpirationDurationInSeconds: 3  # Eureka Server在收不到服务实例的心跳后将其剔除的时间，默认为90秒
  client:
    registryFetchIntervalSeconds: 3
    instanceInfoReplicationIntervalSeconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka服务器地址

server:
  port: 8080 # Gateway服务器端口

logging:
  config: classpath:logback.xml
  level:
    com.mishu: info
`

**Comment by GhostBoyBoy** [comment]
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      clients:
        app1:
          hint:
            enable: true
            gray: 100
        app2:
          hint:
            enable: false
            gray: 100

    gateway:
      httpclient:
        response-timeout: 300s

      routes:
        - id: app1-serv
          uri: lb://app1 # 使用Eureka服务名负载均衡
          predicates:
            - Path=/app1/**
          filters:
            - RewritePath=/app1(?<segment>/?.*), $\{segment}
            - AddNginxRequestHeader=X-Real-IP,$
        - id: app2
          uri: lb://app2
          predicates:
            - Path=/app2/**
          filters:
            - RewritePath=/app2(?<segment>/?.*), $\{segment}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3  # 服务实例向Eureka Server发送心跳的时间间隔，默认为30秒
    leaseExpirationDurationInSeconds: 3  # Eureka Server在收不到服务实例的心跳后将其剔除的时间，默认为90秒
  client:
    registryFetchIntervalSeconds: 3
    instanceInfoReplicationIntervalSeconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka服务器地址

server:
  port: 8080 # Gateway服务器端口

logging:
  config: classpath:logback.xml
  level:
    com.mishu: info

**Comment by GhostBoyBoy** [comment]
```
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      clients:
        app1:
          hint:
            enable: true
            gray: 100
        app2:
          hint:
            enable: false
            gray: 100
    gateway:
      httpclient:
        response-timeout: 300s
      routes:
        - id: app1-serv
          uri: lb://app1 # 使用Eureka服务名负载均衡
          predicates:
            - Path=/app1/**
          filters:
            - RewritePath=/app1(?<segment>/?.*), $\{segment}
            - AddNginxRequestHeader=X-Real-IP,$
        - id: app2
          uri: lb://app2
          predicates:
            - Path=/app2/**
          filters:
            - RewritePath=/app2(?<segment>/?.*), $\{segment}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3  # 服务实例向Eureka Server发送心跳的时间间隔，默认为30秒
    leaseExpirationDurationInSeconds: 3  # Eureka Server在收不到服务实例的心跳后将其剔除的时间，默认为90秒
  client:
    registryFetchIntervalSeconds: 3
    instanceInfoReplicationIntervalSeconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka服务器地址

server:
  port: 8080 # Gateway服务器端口

logging:
  config: classpath:logback.xml
  level:
    com.mishu: info
```
