### ISSUE TITLE
Spring Cloud Gateway 中配置路由的 metadata 不生效（Map<String, Object> 配置 Number 值，获取到的类型为 String）

### ISSUE THREAD

**Issue by oktfolio** [apolloconfig/apollo#4990]
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

在 Spring Cloud Gateway 中配置路由的 metadata，获取到的值为 String，应该是 Number 类型，导致该配置无法生效。

**复现**

通过如下步骤可以复现：

1. Spring Cloud Gateway 项目配置 yaml
```yaml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      - id: xx
        uri: xxx
        predicates:
        - Path=xxx
        filters:
        - StripPrefix=1
        metadata:
          response-timeout: 1
          connect-timeout: 200
```
2. 启动 Spring Cloud Gateway 项目，访问已配置路由的接口，超时时间未生效。

Spring Cloud Gateway 中自动配置的 GatewayProperties#routes 为 RouteDefinition，RouteDefinition 中 metadata 类型为 Map<String, Object>。

而最终通过下面代码获取到的 responseTimeoutAttr 类型是 String，导致该配置无法生效。
```java
private Duration getResponseTimeout(Route route) {
		Object responseTimeoutAttr = route.getMetadata().get(RESPONSE_TIMEOUT_ATTR);
		if (responseTimeoutAttr != null && responseTimeoutAttr instanceof Number) {
			Long routeResponseTimeout = ((Number) responseTimeoutAttr).longValue();
			if (routeResponseTimeout >= 0) {
				return Duration.ofMillis(routeResponseTimeout);
			}
			else {
				return null;
			}
		}
		return properties.getResponseTimeout();
	}
```

该配置项是通过 `DefaultConfig#getProperty(String key, String defaultValue)` `System.getenv(key)` 读取的，这里返回的类型恒为 String。

根据源码来看，类型为 Map<String, Object>，配置为 String:Number 的应该都会存在这种问题。

**期望**

对于 ConfigurationProperties 中类型为 Map<String, Object> 的成员，若配置值为 Number，map 中值的类型也应该是 Number。

### 额外的细节和日志

- 版本：com.ctrip.framework.apollo:apollo-client: 2.1.0
- 错误日志
- 配置：
- 平台和操作系统
